# Generated by Django 5.2.12 on 2026-04-02 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_a', models.ImageField(upload_to='ai_faces/', verbose_name='Изображение A')),
                ('image_b', models.ImageField(upload_to='ai_faces/', verbose_name='Изображение B')),
                ('correct_answer', models.CharField(choices=[('A', 'Изображение A'), ('B', 'Изображение B')], max_length=1, verbose_name='Где ИИ')),
                ('explanation', models.TextField(verbose_name='Объяснение')),
            ],
            options={
                'verbose_name': 'AI-задача',
                'verbose_name_plural': 'AI-задачи',
            },
        ),
        migrations.CreateModel(
            name='TheoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('price', models.IntegerField(default=1, verbose_name='Цена (монеты)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('HEX', 'HEX-Снайпер'), ('AI', 'Детектор ИИ')], max_length=3, verbose_name='Тип игры')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Заработано монет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата игры')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=5, verbose_name='Монеты')),
                ('unlocked_theories', models.ManyToManyField(blank=True, related_name='unlocked_by', to='core.theoryitem', verbose_name='Разблокированные статьи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
