# Generated by Django 5.2.12 on 2026-04-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_theoryitem_cover_alter_theoryitem_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('HEX', 'HEX-Снайпер'), ('AI', 'Детектор ИИ'), ('HSL', 'HSL-Мастер')], max_length=3, verbose_name='Тип игры'),
        ),
    ]
