# Generated by Django 5.2.12 on 2026-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theoryitem_author_alter_gamesession_game_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AITask',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('HEX', 'HEX-Снайпер'), ('HSL', 'HSL-Мастер')], max_length=3, verbose_name='Тип игры'),
        ),
    ]
